////
 Copyright (c) 2018 IBM Corporation and others.
 Licensed under Creative Commons Attribution-NoDerivatives
 4.0 International (CC BY-ND 4.0)
   https://creativecommons.org/licenses/by-nd/4.0/
 Contributors:
     IBM Corporation
////

== Starting and preparing your cluster for deployment

Start your {kube} cluster.

****
[.tab_link]
[#windows1_link]
`*WINDOWS*`
[.tab_link]
[#mac1_link]
`*MAC*`
[.tab_link]
[#linux1_link]
`*LINUX*`

[.tab_content]
[#windows1_section]
--
Start your Docker Desktop environment.

ifdef::docker-desktop-description[]
{docker-desktop-description}
endif::[]
--

[.tab_content]
[#mac1_section1]
--
Start your Docker Desktop environment.

ifdef::docker-desktop-description[]
{docker-desktop-description}
endif::[]
--


[.tab_content]
[#linux1_section1]
--
Run the following command from a command line:

[subs="attributes"]

ifdef::minikube-start[]
{minikube-start}
endif::[]
ifndef::minikube-start[]
minikube start
endif::[]

ifdef::minikube-description[]
{minikube-description}
endif::[]

--


Next, validate that you have a healthy {kube} environment by running the following command from the command line.

```
kubectl get nodes
```

This command should return a `Ready` status for the master node.


[.tab_link]
[#windows2_link]
`*WINDOWS*`
[.tab_link]
[#mac2_link]
`*MAC*`
[.tab_link]
[#linux2_link]
`*LINUX*`

[.tab_content]
[#windows2_section]
--
You do not need to do any other step.
--


[.tab_content]
[#mac2_section]
--
You do not need to do any other step.
--


[.tab_content]
[#linux2_section]
--
Run the following command to configure the Docker CLI to use Minikube's Docker daemon.
After you run this command, you will be able to interact with Minikube's Docker daemon and build new
images directly to it from your host machine:

```
eval $(minikube docker-env)
```
--
****
