////
 Copyright (c) 2018 IBM Corporation and others.
 Licensed under Creative Commons Attribution-NoDerivatives
 4.0 International (CC BY-ND 4.0)
   https://creativecommons.org/licenses/by-nd/4.0/
 Contributors:
     IBM Corporation
////
== Prerequisites

Before you begin, the following tools must be installed:


First, you need a containerization software for building containers. {kube} supports various container runtimes. You will use `Docker` in this guide. For Docker installation instructions, refer to the official https://docs.docker.com/install/[Docker documentation^].

****
[system]#*{win} | {mac}*#

Use Docker Desktop, where a local {kube} environment is preinstalled and enabled. If you do not see the _{kube}_ tab, then upgrade to the latest version of Docker Desktop.

Complete the setup for your operating system:

  - Set up https://docs.docker.com/docker-for-windows/#kubernetes[Docker Desktop for Windows^].
  - Set up https://docs.docker.com/docker-for-mac/#kubernetes[Docker Desktop for Mac^].

After you complete the Docker setup instructions for your operating system, ensure that {kube} (not Swarm) is selected as the orchestrator in Docker Preferences.

[system]#*{linux}*#

You will use `Minikube` as a single-node {kube} cluster that runs locally in a virtual machine.
For Minikube installation instructions, see the https://github.com/kubernetes/minikube#installation[Minikube documentation^]. Be sure to read the https://github.com/kubernetes/minikube#requirements[Requirements^] section, as different operating systems require different prerequisites to run Minikube.

****
