name: Get builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Call test action
      shell: pwsh
      run: |
          $uri = "https://api.github.com/repos/gkwan-ibm/guides-common/dispatches"
          $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
          $headers.Add("Authorization","token ${{ secrets.GK_TOKEN }}")
          $headers.Add("Accept", "application/vnd.github.v3+json")
          $headers.Add("Content-Type", "application/json")
          $body = "{`"event_type`":`"daily-build`",`"client_payload`":{`"dev-date`": `"2020-11-17_1100`", `"java`": `"1.8`"}}"
          Invoke-RestMethod -Uri $uri -Headers $headers -Body $body -Method POST
